### ISSUE TITLE
実施が遅れているゆるDOの順序がチェックを入れると遅延期間順にならなくなる

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#100]
何順になっているかがわからないのですが...序列が変更します...

**Comment by pom-hiro10** [comment]
https://user-images.githubusercontent.com/64677343/230116648-71f73ec5-86ec-42fe-a1c4-ab40c5181d67.mp4

**Comment by pom-hiro10** [comment]
![Screenshot_20230405-214421](https://user-images.githubusercontent.com/64677343/230116744-c1eb4f86-31a2-4584-82e6-3a07d282a345.png)

**Comment by Murasya** [comment]
実施予定日の逆順で置いてたので、完了後もそれの名残でその順番になっちゃってました。
