### ISSUE TITLE
達成日の変更ができない場合とできる場合が存在する

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#103]
![Screenshot_20230419-151746](https://user-images.githubusercontent.com/64677343/232984172-97c1d455-fa66-4afd-8079-d128e791d083.png)
次へがタップできない。
できるものもある。区別は不明…

**Comment by Murasya** [comment]
まだ一度も完了したことがないものの達成日を変更しようとエラー出てましたー
