### ISSUE TITLE
google playから現状インストールできるverだと広告が表示されない

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#110]

**Comment by Murasya** [comment]
自分の環境だと普通に広告表示されるんですが、なんでですかね？

**Comment by pom-hiro10** [comment]
https://github.com/Murasya/yurudo/assets/64677343/44536f5d-52f1-4037-bbe3-ce4fa41a07ab

タスク作成後に毎回表示っていう設定だよね？
前はでてたんだけど、でなくなっちゃった

**Comment by Murasya** [comment]
多分これは見過ぎてでなくなっちゃっただけな気がしますね

**Comment by pom-hiro10** [comment]
![image](https://github.com/Murasya/yurudo/assets/64677343/3c38406d-a2f1-4697-ac30-8d343a80f09b)
なるほど。広告収入って結構はいるんだなあとも思いました。

**Comment by pom-hiro10** [comment]
最近広告出てきたので、見すぎてたパターンみたいです。
