### ISSUE TITLE
【検討】チェックボタンの左側をタップしたときに編集画面がでるのが違和感

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#113]
https://github.com/Murasya/yurudo/assets/64677343/147aeaa2-ea21-4571-b523-f90a6680a1b0

添付動画のように、チェックボタンの左、上、下側を押すと編集画面になる。左側全て☑ボタンとして機能してもいいのではないか。
スマホならば、そこまで違和感はないかもだが、タブレットや横広タイプのスマホなら誤タップ感を生むかも？

**Comment by Murasya** [comment]
とりあえず範囲を広げてリップルつけてみました。

**Comment by pom-hiro10** [comment]
今ってどれくらいの範囲になっている？もう少し範囲を広げることもできますでしょうか？もし範囲を広げると不具合とかあるならばそれも教えてもらえたら！
リップルに関してはチェックボックスUIとして、enhancementに新しいissueとして置いておきます

**Comment by Murasya** [comment]
リップルと同じ範囲にしてます
