### ISSUE TITLE
通知のアイコンが修正されていない

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#118]
https://project-to-ten.slack.com/archives/GV46JG6JD/p1697737533653059?thread_ts=1695370436.337249&cid=GV46JG6JD
この状況と変化していない。ほんとはアイコンとかが出る予定なんだよね？

**Comment by Murasya** [comment]
そうなんです、シミュレータだとうまく表示されてるんですけど、実機だと出ないので苦戦してます。
<img width="314" alt="スクリーンショット 2023-11-03 15 33 28" src="https://github.com/Murasya/yurudo/assets/33850366/10d18843-5dcb-495a-9c40-736e1cf02d81">
<img width="306" alt="スクリーンショット 2023-11-03 15 33 41" src="https://github.com/Murasya/yurudo/assets/33850366/a54f116b-4a8f-465e-9bf6-70be384762c2">
