### ISSUE TITLE
タスク作成時のスパンと必要時間がドラムロールになっていない

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#128]
本来はドラムロールのはずなのだが、ドロップからの選択式になっている
![383206_0](https://github.com/Murasya/yurudo/assets/64677343/6dfbabc4-d403-407d-9a48-4656f5d4cdbb)
![383207_0](https://github.com/Murasya/yurudo/assets/64677343/0e6bb96b-9688-4042-93c9-5110e8b1fe2a)

**Comment by Murasya** [comment]
ドラムロールの部分をプラグイン使ってたんですけど、これが非対応になっちゃったのでドロップダウンにさせてください
もし何か問題あれば教えてください

**Comment by pom-hiro10** [comment]
承知です！別途細かいデザイン部分でここ関連のissue作ります
