### ISSUE TITLE
スパンの設定で月の際に、〇月の〇を選ぶ際にやや挙動がゆっくり

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#134]
https://github.com/Murasya/yurudo/assets/64677343/836fcc3f-c0ab-4142-80c1-be005388a2b0

**Comment by Murasya** [comment]
アニメーションがついてる関係上どうしても遅くなります。
改善案としては、メニューの高さに最大値をつけることですが、どちらがいいでしょうか？
↓高さ制限をつけたバージョン
![Image](https://github.com/user-attachments/assets/fe34ccba-2b7d-47c5-96c6-4b38329145b1)

**Comment by pom-hiro10** [comment]
高さ制限を付けたバージョンの画像が表示できず、再度上げてもらってもよいでしょうか？

**Comment by Murasya** [comment]
https://github.com/user-attachments/assets/997e913c-6c75-4351-ab53-6944c38e6591
