### ISSUE TITLE
実施が遅れているゆるDOの並び順について

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#137]
もともとは遅延期間の短い順に並んでいたが、現在はなっていない。
短い順に列挙。
![397319_0](https://github.com/user-attachments/assets/c6e824f7-cb8d-44cb-8544-8c0272c0f39f)

**Comment by Murasya** [comment]
デバッグに期限を決めてタスクを作れる機能を追加しておきました
