### ISSUE TITLE
実施日選択のカレンダーの縦幅が狭くなった

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#138]
他のカレンダーでもそうだが、縦幅および横幅も？狭くなりタップするのがやりづらくなった。画像の赤い部分。

![397320_0](https://github.com/user-attachments/assets/91bd805d-e708-42af-aa58-b7eb86997b2b)

**Comment by Murasya** [comment]
カレンダー自体無くなったのでクローズします
