### ISSUE TITLE
未来のタスクの実施予定日の変更について

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#140]
①表示が9/10となっているが、編集しようとタップすると9/8になっている
②一度選択後、再度編集しようとすると、「この実施予定日は変更できません」とでて編集ができない。
https://github.com/user-attachments/assets/3b88668a-0f22-4bab-8a02-c49bae0966c7

**Comment by Murasya** [comment]
これの修正にあたって、
9/10が直近期限の毎日タスクで、9/11のタスクの実施予定日の変更
をできるようにしました。
何か問題あれば教えてください。
