### ISSUE TITLE
[デザイン]カテゴリの編集

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#141]
下線と文字色が同じせいか、タップして編集できるように思いづらい。
![397326](https://github.com/user-attachments/assets/bdcd2978-27a8-4e7f-9bf7-0bf110031e35)

**Comment by pom-hiro10** [comment]
よりよくするためなのですが、分類のすでに記載されている部分の語尾のところまでしかいまはタップが聞かない状態になっていると思うのですが、そのタップ範囲をより長くできるといいかなと

「英語」という分類があったとして、左側の2文字分くらいしかタップ有効域がないので。。。

**Comment by Murasya** [comment]
タップ範囲は右の方も反応してましたが、確かに狭そうだったので、広くしてみました

**Comment by pom-hiro10** [comment]
![Image](https://github.com/user-attachments/assets/1934ee62-03e9-49ef-8d32-5ffcf2388296)
赤丸の部分のスペースを狭くするようにお願いします。

**Comment by pom-hiro10** [comment]
@daiiichi5 
英語版での確認もお願いします

**Comment by daiiichi5** [comment]
@pom-hiro10 
確認完了済みで、問題ございません。
