### ISSUE TITLE
未来に存在しているタスクの実施予定日を前に実施された日やその前の日程に変更可能になっている

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#146]
前の実施日以前には設定不可、昨日より前には設定不可でないとおかしくなっちゃう

**Comment by pom-hiro10** [comment]
これをチェックしていた時に2点バグがあったので、ここに記載します

前提：今日の日付 10/12
①10/11実施、次回10/25のタスクの実施予定日を10/12にした。
10/12のこの日のゆるDOには表示されなかった。週表示で表示すると表示された。(添付動画参照https://github.com/user-attachments/assets/9a07a9d1-0d07-4cbe-b8f6-746be534dcb7
)
⇒日表示でも表示されるようにする。

②積みタスクに入っているタスクの未来のものの実施予定日を10/12にした。
積みタスクからタスクは消え、この日のゆるDOにタスクが表示された。
⇒積みタスクがある場合は、その積みタスクの未来のものは実施予定日を変更できないことにする。積みタスク自体は、積みタスクから未来に動かすことは可能。

**Comment by Murasya** [comment]
①再現しませんでした
動画が表示されなかった後からになっていて、どうやったら再現できるかわかりませんでした

②LINEでも言いましたが、仕様が複雑なので未来の日付は積みタスクを非表示にする方針にできないでしょうか？

**Comment by Murasya** [comment]
https://github.com/Murasya/yurudo/issues/159
↑の対応で①も治った気がします

②は非表示で実装してみました
やっぱり使いにくいとかあればまた相談させてください
