### ISSUE TITLE
【英語表記】新規ゆるDo作成

### ISSUE THREAD

**Issue by daiiichi5** [Murasya/yurudo#150]
![Image](https://github.com/user-attachments/assets/e6635135-c6e6-409b-9f0d-7d467153e0ad)

**Titleセクション**：例文を以下英語表記に変更
e.g. Replace closet moth repellent (once every 6 months)

**Spanセクション**："Span"の文言を"Frequency"に変更

**Required Timeセクション** : 

- "Required Time"の文言を"Frequency"に変更
- 1文字分スペースを空け、"Minutes"のMを小文字にして、"35 minutes"のような形式にする

**First Planned Execution Dateセクション** : 

- "First Planned Execution Date"の文言を"Start Date"に変更
- 日付の表示形式を"YYYY-MM-DD"に変更

**Comment by Murasya** [comment]
5minutes のスペースをあけ、5 minutesになるようにしました

**Comment by daiiichi5** [comment]
![Image](https://github.com/user-attachments/assets/6c5703de-2128-4ffe-9986-fafb10695550)

改行が必要のため、再度変更

**Comment by daiiichi5** [comment]
Yuru-DOにsを追加
Yuru-DOsに変更

**Comment by daiiichi5** [comment]
@Murasya 
Please set frequency. Onceになっていて、改行したかったので、\nを以下のように加えたのですが、
これで問題なく下に改行されますかね...?


"setSpan": "Please set frequency \nOnce in",
  "atOnce": "",

**Comment by Murasya** [comment]
@daiiichi5 手元で試してみたらされそうです![Image](https://github.com/user-attachments/assets/b7b92a57-8855-411f-bc7c-c2da3a1dba14)

**Comment by daiiichi5** [comment]
@Murasya 
確認ありがとうございます🙇‍♂️
