### ISSUE TITLE
TargetSDKを34に

### ISSUE THREAD

**Issue by Murasya** [Murasya/yurudo#157]
Androidのアップデートに必要

**Comment by Murasya** [comment]
全体的に動作が問題なければOK

**Comment by pom-hiro10** [comment]
@daiiichi5 
英語版での確認もお願いします

**Comment by daiiichi5** [comment]
@pom-hiro10 @Murasya 
英語版の何を確認すればよいですか？

**Comment by Murasya** [comment]
@daiiichi5 
動いてれば問題ないので、クラッシュとかしてなければこのチケットはCloseしちゃって大丈夫です！

**Comment by daiiichi5** [comment]
@daiiichi5 
Okです。動いてます
