### ISSUE TITLE
タスク作成時に分類を選択しても反映されない

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#166]
選択ボタンを押した後にOKを押しても「なし」のままとなっている。
→反映されるように修正お願いします。

https://github.com/user-attachments/assets/822271a6-3ed4-47ff-9e44-60447d96b0a0

**Comment by Murasya** [comment]
多分↓のせいで画面がバグってた？まだ再現するようなら教えてください
https://github.com/Murasya/yurudo/issues/164
