### ISSUE TITLE
フィードバック機能

### ISSUE THREAD

**Issue by Murasya** [Murasya/yurudo#20]
メールでnoteappm@gmail.comに送るようにする

**Comment by pom-hiro10** [comment]
いまメール1通送ったので、それで問題なければcloseしていただいて大丈夫です

**Comment by Murasya** [comment]
OK

<img width="650" alt="image" src="https://user-images.githubusercontent.com/33850366/228768673-8e38529a-4471-4bcc-90d8-c09705b1c76b.png">
