### ISSUE TITLE
[home] 先回りして実施したタスクが消えてしまう

### ISSUE THREAD

**Issue by Shiorito** [Murasya/yurudo#41]
3/28に、3/30に予定されているタスクを先回りして実施した(チェックを入れた)ところ、
3/28にも3/30にも実施したはずのタスクが表示されなくなりました

3/28に実施済みタスクとして表示されるのが正解？

**Comment by Murasya** [comment]
@Shiorito @pom-hiro10 
「3/28に実施済みタスクとして表示」にすると、3/30の画面から消えてユーザー的にはパッと見消えた感じになりそうですけどどうでしょうか？

**Comment by pom-hiro10** [comment]
![image](https://user-images.githubusercontent.com/64677343/228305212-08b14501-bc8a-4c7f-abae-334d480f56a4.png)

**Comment by pom-hiro10** [comment]
上のように場合分けが必要かなと
未来に関しては今回のα版ではチェックは入れられても入れられなくても、いいかなと思います
↑の場合分けを実装するのが面倒であれば、明日以降のものには現段階では☑を入れられないようにする必要があるかと。

**Comment by Murasya** [comment]
未来のゆるDO完了に対応したのでこいつも治ってると思います。
