### ISSUE TITLE
[new task category]分類にキャッシュを削除以降もデフォルトで「既定の色」と「勉強」と数字が設定されている

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#44]
青→既定の色、黄→勉強、ピンク→2、、、となっている。
デフォルトの状態では好きな分類をつけられますでお願いします。

**Comment by Murasya** [comment]
これですが、AndroidのDBの保存場所が悪かったみたいで、キャッシュやアプリの削除じゃ中身のDBが消えてないみたいです。
デフォルトではつかないので大丈夫です。
