### ISSUE TITLE
ゆるDO一覧でのチェックボックスとラジオボタンの色

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#47]
【優先度低】ライトグリーンのようになっているが、XDに準拠する。

![336241](https://user-images.githubusercontent.com/64677343/228220669-1e0bc28a-a3ac-450d-ad2c-5cf886968ff2.jpg)
![336240](https://user-images.githubusercontent.com/64677343/228220688-7053d7ba-9669-435f-ab1a-988a3709e67b.jpg)

**Comment by Murasya** [comment]
ラジオボタンの形は再現できませんが、色は変更しました
