### ISSUE TITLE
【要検討】過去の日程でのタスク作成は必要か

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#51]
過去の日程でのタスク作成は想定していなかったが、現状ではできる状態にある。(デバックのために過去の日程を作成できるようになっていたとしたらすいません...)
テストで過去の日程でタスク作成をするとバグが生じているが、複雑なのでよくわからない。
バグ例
・過去の日程で作成すると過去の日程に生成される場合とされない場合がある。
・過去の日程を開始日とすると、表示が狂う
2/28に1週に1回のものを作成すると2/28(home weekのみに表示される、home dayには表示されない)と実施されなかったゆるDOに表示される
3/23に3日に1回のものを作成するとhome dayだと3/23と実施されなかったゆるDO、home weekだと3/23のみに表示される

**Comment by Murasya** [comment]
作成のバグじゃなくて、表示のバグですね、、、
> 2/28に1週に1回のものを作成すると2/28(home weekのみに表示される、home dayには表示されない)と実施されなかったゆるDOに表示される

これは2/21と実施されなかったゆるDOに表示

> 3/23に3日に1回のものを作成するとhome dayだと3/23と実施されなかったゆるDO、home weekだと3/23のみに表示される

これは3/26と実施されなかったゆるDOに表示
で合ってますか？

**Comment by pom-hiro10** [comment]
「過去のタスクで未実施のものは直近のものだけ表示」という原則に従うと

>2/28に1週に1回のものを作成すると2/28(home weekのみに表示される、home dayには表示されない)と実施されなかったゆるDOに表示される
→今日が3/29だとすると、2/28から1週間に1回のスパンでタスクが進んできたとすると3/28が直近なので、3/28,4/4.....と実施されなかったゆるDOに表示されるのが正しいです

>3/23に3日に1回のものを作成するとhome dayだと3/23と実施されなかったゆるDO、home weekだと3/23のみに表示される
→今日が3/29だとすると、3/26,4/1....と実施されなかったゆるDOに表示されるのが正しいです

**Comment by pom-hiro10** [comment]
ただ過去の日付にさかのぼってタスクを作成することを想定してなかったのほうが正しいですかね...

**Comment by Murasya** [comment]
https://project-to-ten.slack.com/archives/GV46JG6JD/p1680053514882169
これ含めて考えると結局どうしますか？
できないようにするなら、ダイアログ上で「OK」を押した時に弾くことはできます。

**Comment by Murasya** [comment]
過去の日程でのタスク作成は禁止

<img width="500" alt="image" src="https://user-images.githubusercontent.com/33850366/228755748-9fc8d919-60c5-4e27-a73a-42d4d9f7cbdf.png">

**Comment by pom-hiro10** [comment]
こういう検討
