### ISSUE TITLE
[new task]各項目でpasteする気持ちの長押しをすると、変な表示が残る

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#53]
長い文章を試しに入れようとしてペーストをした際に気づいた。
スパン、必要時間、実施予定日のところで長押しすると、その文字列を選択できてしまう。
説明が難しく...画像参照です。
![336288](https://user-images.githubusercontent.com/64677343/228246735-7c152a9
![336287](https://user-images.githubusercontent.com/64677343/228246774-dc13ca6e-d7a9-46e5-a993-c85cc85fe22e.jpg)
f-f572-46d3-af64-b7ffcb86c251.jpg)

**Comment by Murasya** [comment]
タイトルはできるようになってると思うんですけど

**Comment by pom-hiro10** [comment]
クリップボードに何もない状態でやっているだけだった！問題なしです。
