### ISSUE TITLE
[list]タスク名が長い場合に、右下の表示に文字がかぶっている

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#55]
被らないところまで位の表示にして、表示しきれない部分は...に

**Comment by pom-hiro10** [comment]
![336327](https://user-images.githubusercontent.com/64677343/228297303-ca94bd9c-67e1-4440-b3b1-583f9a6613a9.jpg)

**Comment by Murasya** [comment]
@Shiorito
すみません、技術的に難しくてここはデザイン変えていただけないでしょうか
2行目の途中で...にするのが難しいです。

**Comment by Murasya** [comment]
ひとまず少しずらして被らないように修正しました

**Comment by Shiorito** [comment]
@Murasya 
見落としてました、すみません！
修正してくださったものを確認したのですが、左側の分類のカラーがずれてしまっているようです

ちなみに、2行より多い分量の場合はボックス自体のサイズ(縦幅)が行数に合わせて大きくなるようにするのは、難しいでしょうか…？今
![IMG_1157](https://user-images.githubusercontent.com/63578821/229348574-76f5d0bb-7d92-43fd-98f4-21b238d24823.PNG)
じゃなくても良いのですが

**Comment by Murasya** [comment]
@Shiorito 
できます！こういう感じでどうでしょう？

![image](https://user-images.githubusercontent.com/33850366/229350503-bd3e877b-7ba0-4c1d-8d8c-2c453d5b3ad6.png)

**Comment by Shiorito** [comment]
@Murasya 
ありがとうございます！いい感じです！

右下のテキスト(1週に1回/195分)とタスク名のテキストの間をもう少しあけられるでしょうか(多分10〜12pxくらい)

**Comment by Murasya** [comment]
@Shiorito 
いかがでしょう？
![image](https://user-images.githubusercontent.com/33850366/229350882-8b292bdb-43e2-4f98-858c-29077d9c6f02.png)

**Comment by Shiorito** [comment]
@Murasya 
ありがとうございます！良きです🙆‍♀️
