### ISSUE TITLE
[home] 過去のタスクどうするか問題

### ISSUE THREAD

**Issue by Murasya** [Murasya/yurudo#62]
現状
- 直近1回分のみ表示

現状の問題点
- 昨日のもののチェックを入れ忘れることはわかるが、2日以上遡ってチェックを入れたくなるとは考えにくい
- 今のデータ構造で直近1回ぶんだけ表示するのが難しい
- 元々の予定だった日以外を選べない → 今が1/3だとして、1/1実施予定で1/2にやった場合チェック入れられない

改善案1
- 過去の未実施のものは全て、今日のページの実施が遅れたゆるDOにのみ表示
- 実施が遅れたゆるDOからチェック入れると完了日も選べる

改善案2
- 過去の未実施のもの全てを過去のページに表示する（実施が遅れたゆるDOにも）
- どれかにチェックを入れた場合は、チェックを入れたものだけ残り、未実施だったものは全て消えて、新しく設定した実施予定日からスタート

**Comment by Murasya** [comment]
関連issue #61 #51

**Comment by Murasya** [comment]
Slackスレッド:https://project-to-ten.slack.com/archives/GV46JG6JD/p1680053514882169

**Comment by pom-hiro10** [comment]
記録
![image](https://user-images.githubusercontent.com/64677343/229047346-e2e8cd1e-8733-4ce2-abb5-fb6748eed390.png)
![image](https://user-images.githubusercontent.com/64677343/229047400-2ab5c547-e82e-4721-9585-7bb3f935e4d4.png)
![image](https://user-images.githubusercontent.com/64677343/229047485-cd44fce2-3149-4d40-9551-d227ca2f71f6.png)
![image](https://user-images.githubusercontent.com/64677343/229047550-a149edf2-2251-4b85-a372-f3ec7065cb08.png)
