### ISSUE TITLE
通知が来ない

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#63]
リマインドするに☑を入れていたが、通知が来なかった。

**Comment by Murasya** [comment]
@pom-hiro10 
今まで通知きたことないですか？

**Comment by pom-hiro10** [comment]
いままで通知きたことない！

**Comment by Murasya** [comment]
@pom-hiro10 
なんでだろう、、、バイト先から借りてたAndroidでは通知きてたんですけど
通知許可はしてますか？

**Comment by pom-hiro10** [comment]
@Murasya 
通知許可オフになってました！申し訳ない。
最近のAndroidは自動で権限切りしてくるので、「アプリの起動時」と「タスク作成画面でリマインドするに☑が入ってる場合」に以下のような画面を出すこと可能ですか？

**Comment by pom-hiro10** [comment]
![Screenshot_20230331-150232](https://user-images.githubusercontent.com/64677343/229045595-36d4aaaa-2a8f-40a7-93f4-bad7204884af.png)

**Comment by pom-hiro10** [comment]
朝9時に当日のタスクの通知が来るんだよね？明日の朝にチェックします

**Comment by pom-hiro10** [comment]
通知来ました。
今日のゆるDOに何もなくても(実施されなかったゆるDOは存在)通知が来るようなのだけど、それはデフォルトとして問題ないかな？
今後修正必要ならば、修正する形で。とりあえずは問題なしです。
