### ISSUE TITLE
[detail] 未来の実施予定日は変更できないようにする

### ISSUE THREAD

**Issue by Murasya** [Murasya/yurudo#69]
https://project-to-ten.slack.com/archives/GV46JG6JD/p1680076358456969

**Comment by pom-hiro10** [comment]
次回のもののみは変更できるようにする。2,3個先のものは変更できない。
当日に未チェックのものがあり、チェックを入れた場合には、次回の実施予定日がスパンに基づくものではなく、変更されたものを表示する。

**Comment by Murasya** [comment]
@pom-hiro10 
データ的に、未チェックのものしか変更できないです。

遅れたタスク→遅れたゆるDOのところからだけ変更可能
今日のタスク→今日のページからだけ変更可能
明日以降のタスク→未チェック1つ目のものだけ変更可能

ではダメですか？

**Comment by pom-hiro10** [comment]
@Murasya
今回は↑で問題ないです！
将来的には、直近の予定を組み替えることはやりたいとき(今日のタスクにチェックを入れる前でも)できた方がいいと思うので変更で来たら良いかと思います。とりあえず使ってみて...ってとこですかね。
