### ISSUE TITLE
スパンの週の設定ができない

### ISSUE THREAD

**Issue by Murasya** [Murasya/yurudo#7]

**Comment by pom-hiro10** [comment]
できるようになってました！
ここ関連で追加の内容はissueに書いた方がいいでしょうか？とりあえず↓に残しときます。
・スパンの漢数字と数字の統一
タスク作成画面では「1週に一回」となっているが「1週に1回」のほうがいいと思います。
・タスク作成画面とタスク編集画面の表示統一
タスク作成画面では「1週に一回」となっているがタスク編集画面では「7日に1回」になっている。
「1週に1回」に統一。

**Comment by Murasya** [comment]
修正しました。
