### ISSUE TITLE
[new task]リマインドするに☑をいれていても通知リクエストが出ない

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#76]
アプリインストール時は通知の送信許可出る

**Comment by Murasya** [comment]
@pom-hiro10 
一回通知許可したらもう出なくないですか？
Androidって毎回許可必要なんですか？

**Comment by pom-hiro10** [comment]
許可をオフにしている状態で、リマインドするに☑をいれても通知リクエストがでないってことです！

**Comment by Murasya** [comment]
@pom-hiro10 
タスク作成するときにリクエストする設定にしてるんですけど、多分1回拒否したらスマホの仕様上もう出せないです。

**Comment by pom-hiro10** [comment]
なるほど、承知。そしたらこれはこれで！
