### ISSUE TITLE
[list]listでタスク作成、削除、編集後にhomeに戻ってしまう、listに戻るように

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#79]
過去にも上げたissueで対応されていたはずが戻っていました

**Comment by Shiorito** [comment]
削除しても、タスクの編集画面から移動しなくなってしまっていました
理想は、以下です！
①homeからタスクの編集画面に遷移して削除した場合→homeへ
②listからタスクの編集画面に遷移して削除した場合→listへ
