### ISSUE TITLE
[menu] 「アプリの使い方」は今回は非表示にする？

### ISSUE THREAD

**Issue by Shiorito** [Murasya/yurudo#81]
@pom-hiro10 @Murasya
アプリの使い方の中身が今回の申請までにはないと思うので、一旦非表示かなと思っていました認識あってますでしょうか

**Comment by pom-hiro10** [comment]
@Murasya @Shiorito 
本当は簡単な文章レベルでも作れたらいいなと思っていたのですが、作り切れなさそうなので、いったん非表示にしていただけますでしょうか...
