### ISSUE TITLE
実施が遅れているゆるDOの実施日変更で未来の日程を選択することができるようになっている

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#95]
未来の日程を選択すると実施されなかったゆるDOにチェックが入っていない状態でそのまま残り、実施予定日が未来の日程になっている。また未来の日程にはなにも表示されていない。

未来の日程は選べないようにする。

**Comment by pom-hiro10** [comment]
ゆるDOの方より実行した場合も同様に未来の日程を選ぶことができた。

できないようにする。

**Comment by Murasya** [comment]
@pom-hiro10 
今日or実施遅れを今度の週末やることにしよう！は普通にあると思いますけど

**Comment by Murasya** [comment]
あー理解です。明日の分で修正します。
