### ISSUE TITLE
【検討】完了日の変更を同一タスクの直近実施日より前にできるべきか

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#97]
今日は4/5、直近実施日が4/1だとする。ゆるDOまたは実施されなかったゆるDOからタスクにチェックをいれ、完了日の変更を行い、3/10にした。
現状ではこれを行うことができるが完了日の選択は直近実施日以降の日程のみにすべきか？
いまのところそんなに問題は起きていなさそうなので、今後に考えていこう。

**Comment by Murasya** [comment]
これは割と簡単に実装できそうなのであっても大丈夫です

**Comment by pom-hiro10** [comment]
すでに同一タスクの☑が入っている日に再度次回予定日を設定できたりしちゃうので、完了日の選択は直近実施日以降の日程にしましょう。
時間軸が行ったり来たりしてずれないほうがいいかなと
