### ISSUE TITLE
【要検討】過去に実施済みのゆるDOよりタスクの編集と削除を行えるべきかどうか

### ISSUE THREAD

**Issue by pom-hiro10** [Murasya/yurudo#99]
今起きている問題
4/2に実施済みのタスクがあったとする。それが週に1回のタスクで次回が4/9だとする。
4/2をタップして実施予定日を4/6にした場合に、4/6には表示されず4/9に表示されているものの予定日が4/6になっている。

〇過去のゆるDOの編集について
・現状は他の日程に表示されているゆるDOと同様に編集することができる
・全て☑済みのものなので、編集することは必要なのか、タイトル～必要時間まではよいが、実施予定日は変更できなくて良い気がする
**・実施予定日が変更できるのは未実施のゆるDOが対象でよいのではないか
→実施予定日のところをタップしたら「実施予定日は未実施のもののみ変更することができます」とか**

〇過去のゆるDOの削除について
・現状は他の日程に表示されているゆるDOと同様に編集することができる
・人に見られたくないなどで後から削除対応できても良い気がする

**Comment by Shiorito** [comment]
@pom-hiro10 @Murasya 

①そもそも編集不可
②実施予定日のみ編集できない
のどちらかかなと思いました。個人的にはどちらでも違和感ないです

削除についても上記に連動して、①の場合は不可、②の場合は可で良いと思いました

**Comment by pom-hiro10** [comment]
@Murasya @Shiorito 
昨日実施していて、次の実施日が3か月後とかだと探しづらいかなと思ったので、②はいかがでしょうか
削除もしおりちゃんの言うように可でいいと思います
